services:
  bot:
    image: registry.gitlab.com/pavellukyanov08/voice_transcribot:latest
    container_name: voice_transcribot
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - ./audio:/voice_transcribot/audio
      - ./logs:/voice_transcribot/logs
    networks:
      - voice_transcribot_network

  db:
    container_name: voice_transcribot_db
    image: postgres:15-alpine
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "5488:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
    networks:
      - voice_transcribot_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

volumes:
  postgres_data:

networks:
  voice_transcribot_network:
    driver: bridge