"""Init app

Revision ID: 126f51907460
Revises: 
Create Date: 2026-02-04 11:26:52.199975

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '126f51907460'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('telegram_id', sa.BigInteger(), nullable=False, comment='Telegram ID of user'),
    sa.Column('name', sa.String(), nullable=False, comment='Name of user'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='User created date'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='User updated date'),
    sa.PrimaryKeyConstraint('telegram_id')
    )
    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False, comment='ID of voice message of user'),
    sa.Column('text', sa.String(length=500), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='User created date'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='User updated date'),
    sa.ForeignKeyConstraint(['user_id'], ['users.telegram_id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('messages')
    op.drop_table('users')
    # ### end Alembic commands ###
