"""Removed 'type' (message type) in 'Message' model

Revision ID: 2c18e4d484a5
Revises: a81a4c967170
Create Date: 2026-02-10 17:15:20.576838

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2c18e4d484a5'
down_revision: Union[str, Sequence[str], None] = 'a81a4c967170'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'type')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('type', postgresql.ENUM('VOICE', 'FILE', name='messagetype'), autoincrement=False, nullable=False, comment='Тип сообщения (файл/голосовое)'))
    # ### end Alembic commands ###
