"""Updated 'name' in 'User' model

Revision ID: 5cb1a6d8f681
Revises: bd8a97bc21e9
Create Date: 2026-02-04 15:40:36.880086

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5cb1a6d8f681'
down_revision: Union[str, Sequence[str], None] = 'bd8a97bc21e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_comment='Name of user')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_comment='Name of user')
    # ### end Alembic commands ###
