"""Removed extra field from 'Message' model

Revision ID: 91d2b4fbf276
Revises: 5cb1a6d8f681
Create Date: 2026-02-05 10:48:31.510762

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '91d2b4fbf276'
down_revision: Union[str, Sequence[str], None] = '5cb1a6d8f681'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'file_unique_id')
    op.drop_column('messages', 'file_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('file_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False, comment='ID файла в Telegram'))
    op.add_column('messages', sa.Column('file_unique_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False, comment='Уникальный ID файла'))
    # ### end Alembic commands ###
