"""Added 'type' (message type) in 'Message' model

Revision ID: a81a4c967170
Revises: 91d2b4fbf276
Create Date: 2026-02-10 16:39:38.373750

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import ENUM


# revision identifiers, used by Alembic.
revision: str = 'a81a4c967170'
down_revision: Union[str, Sequence[str], None] = '91d2b4fbf276'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


message_type_enum = ENUM(
    'VOICE', 'FILE',
    name='messagetype'
)

def upgrade() -> None:
    """Upgrade schema."""
    message_type_enum.create(op.get_bind())
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('type', message_type_enum, nullable=False,
                                        comment='Тип сообщения (файл/голосовое)'))
    op.alter_column('messages', 'text',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_comment='Распознанный текст',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('messages', 'text',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_comment='Распознанный текст',
               existing_nullable=False)
    op.drop_column('messages', 'type')
    # ### end Alembic commands ###
