"""Updated 'User' model and added 'Message'

Revision ID: bd8a97bc21e9
Revises: 126f51907460
Create Date: 2026-02-04 15:05:02.963336

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bd8a97bc21e9'
down_revision: Union[str, Sequence[str], None] = '126f51907460'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('file_id', sa.String(length=255), nullable=False, comment='ID файла в Telegram'))
    op.add_column('messages', sa.Column('file_unique_id', sa.String(length=255), nullable=False, comment='Уникальный ID файла'))
    op.add_column('messages', sa.Column('confidence', sa.Float(), nullable=True, comment='Уверенность модели'))
    op.add_column('messages', sa.Column('processing_time', sa.Float(), nullable=False, comment='Время обработки в секундах'))
    op.alter_column('messages', 'id',
               existing_type=sa.INTEGER(),
               comment='ID записи транскрипции',
               existing_comment='ID of voice message of user',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('messages', 'text',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.Text(),
               comment='Распознанный текст',
               existing_nullable=False)
    op.alter_column('messages', 'user_id',
               existing_type=sa.BIGINT(),
               comment='ID пользователя',
               existing_nullable=False)
    op.alter_column('messages', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Время создания записи',
               existing_comment='User created date',
               existing_nullable=False)
    op.alter_column('messages', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Время обновления записи',
               existing_comment='User updated date',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('messages', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='User updated date',
               existing_comment='Время обновления записи',
               existing_nullable=False)
    op.alter_column('messages', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='User created date',
               existing_comment='Время создания записи',
               existing_nullable=False)
    op.alter_column('messages', 'user_id',
               existing_type=sa.BIGINT(),
               comment=None,
               existing_comment='ID пользователя',
               existing_nullable=False)
    op.alter_column('messages', 'text',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=500),
               comment=None,
               existing_comment='Распознанный текст',
               existing_nullable=False)
    op.alter_column('messages', 'id',
               existing_type=sa.INTEGER(),
               comment='ID of voice message of user',
               existing_comment='ID записи транскрипции',
               existing_nullable=False,
               autoincrement=True)
    op.drop_column('messages', 'processing_time')
    op.drop_column('messages', 'confidence')
    op.drop_column('messages', 'file_unique_id')
    op.drop_column('messages', 'file_id')
    # ### end Alembic commands ###
