"""Removed extra field from 'Message' model

Revision ID: dd1091e9668f
Revises: 91d2b4fbf276
Create Date: 2026-02-05 20:33:16.548704

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dd1091e9668f'
down_revision: Union[str, Sequence[str], None] = '91d2b4fbf276'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'confidence')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('confidence', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True, comment='Уверенность модели'))
    # ### end Alembic commands ###
